
services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "81:80"
    

    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Kafka: O seu broker de mensagens
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # Correto para os seus serviços rodando no host
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # MySQL: O seu banco de dados
  mysql:
    image: mysql:8.0
    container_name: mysql_db_sinapse
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root # Use senhas mais fortes em produção
      MYSQL_DATABASE: sinapse_reports
      MYSQL_USER: user # Ótimo! Usar um utilizador dedicado é uma boa prática.
      MYSQL_PASSWORD: root # Use senhas mais fortes em produção
  

# Definição dos volumes nomeados para persistência de dados
volumes:
  mysql_data: