# Configurações Gerais da Aplicação
server:
  port: 8081
spring:
  application:
    name: report-request-service 
  threads:
    virtual:
      enabled: true 


  datasource:
    url: jdbc:mysql://localhost:3306/sinapse_reports?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root


  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  cloud:
    stream:
      bindings:
        publishReportRequest-out-0:
          destination: report-requests 
          content-type: application/json

    
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
          idempotent: true
          
         
          producer-properties:
            acks: all 
            retries: 3
          
          health-check-interval: 10s 
          health-check-timeout: 5s  